### ISSUE TITLE
pnpm is v9.1.1 is not supporting 

### ISSUE THREAD

**Issue by santoshgistto** [Livog/Payload.3.0.Starter#4]
Error : 
> ERR_PNPM_BAD_PM_VERSION  This project is configured to use v8.15.4 of pnpm. Your current pnpm is v9.1.1

Thanks for this starter project

**Comment by Livog** [comment]
@santoshgistto Hello!

This is known and it seemed to be on `pnpm`s table as I understood it, as it seems to have problems resolving packages. I also saw there was a discussion around it here so seems like the Payload team also are aware (https://discord.com/channels/967097582721572934/1102950643259424828/1235647589483810907). So yeah that's why I kept version 8.

Happy that you like it!
